# Generated by Django 3.2.25 on 2024-07-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outfit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('outfit', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OutfitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.outfit')),
            ],
            options={
                'unique_together': {('outfit', 'category')},
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='categories',
            field=models.ManyToManyField(through='products.OutfitCategory', to='products.Category'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='products',
            field=models.ManyToManyField(through='products.OutfitProduct', to='products.Product'),
        ),
    ]
